version: "3"

services:
  web:
    build: .
    command: bash -c "uvicorn apps:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017-27019:27017-27019 # remove this line on prod